In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("lymphography.csv")

In [4]:
data.head()

3  4  2  1  1.1  1.2  1.3  1.4  ...  2.3  2.4  4.1  8  1.6  1.7  2.5  2.6
0  2  3  2  1    1    2    2    1  ...    3    2    3  4    2    2    2    2
1  3  3  2  2    2    2    2    2  ...    3    3    4  8    3    2    2    7
2  3  3  1  1    1    1    2    1  ...    3    4    4  4    3    1    2    6
3  2  3  1  1    1    1    1    1  ...    2    4    3  5    1    2    2    1
4  2  2  1  1    1    1    1    1  ...    3    3    3  6    3    1    2    4

[5 rows x 19 columns]

In [5]:
data.dtypes

3      int64
4      int64
2      int64
1      int64
1.1    int64
1.2    int64
1.3    int64
1.4    int64
2.1    int64
1.5    int64
2.2    int64
2.3    int64
2.4    int64
4.1    int64
8      int64
1.6    int64
1.7    int64
2.5    int64
2.6    int64
dtype: object

In [6]:
data.isna().sum()

3      0
4      0
2      0
1      0
1.1    0
1.2    0
1.3    0
1.4    0
2.1    0
1.5    0
2.2    0
2.3    0
2.4    0
4.1    0
8      0
1.6    0
1.7    0
2.5    0
2.6    0
dtype: int64

In [8]:
data.describe()

3           4           2  ...         1.7         2.5         2.6
count  147.000000  147.000000  147.000000  ...  147.000000  147.000000  147.000000
mean     2.448980    2.734694    1.551020  ...    1.666667    1.789116    2.605442
std      0.575572    0.813638    0.499091  ...    0.473016    0.409331    1.910884
min      1.000000    1.000000    1.000000  ...    1.000000    1.000000    1.000000
25%      2.000000    2.000000    1.000000  ...    1.000000    2.000000    1.000000
50%      2.000000    3.000000    2.000000  ...    2.000000    2.000000    2.000000
75%      3.000000    3.000000    2.000000  ...    2.000000    2.000000    3.000000
max      4.000000    4.000000    2.000000  ...    2.000000    2.000000    8.000000

[8 rows x 19 columns]

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   3       147 non-null    int64
 1   4       147 non-null    int64
 2   2       147 non-null    int64
 3   1       147 non-null    int64
 4   1.1     147 non-null    int64
 5   1.2     147 non-null    int64
 6   1.3     147 non-null    int64
 7   1.4     147 non-null    int64
 8   2.1     147 non-null    int64
 9   1.5     147 non-null    int64
 10  2.2     147 non-null    int64
 11  2.3     147 non-null    int64
 12  2.4     147 non-null    int64
 13  4.1     147 non-null    int64
 14  8       147 non-null    int64
 15  1.6     147 non-null    int64
 16  1.7     147 non-null    int64
 17  2.5     147 non-null    int64
 18  2.6     147 non-null    int64
dtypes: int64(19)
memory usage: 21.9 KB


In [10]:
data.corr()

3         4         2  ...       1.7       2.5       2.6
3    1.000000  0.139093 -0.366410  ...  0.226420  0.230202  0.548273
4    0.139093  1.000000  0.075729  ...  0.249154  0.077646  0.126047
2   -0.366410  0.075729  1.000000  ... -0.029013  0.036264 -0.086475
1   -0.052014  0.063718  0.418431  ...  0.100855  0.152223  0.199022
1.1  0.214800  0.112556  0.201843  ...  0.158114  0.115594  0.398581
1.2  0.050654  0.225350  0.355043  ...  0.167789  0.139287  0.292434
1.3  0.126366  0.149329  0.346738  ...  0.086603  0.194026  0.232895
1.4  0.400832  0.088397  0.026605  ...  0.019104  0.073437  0.424835
2.1  0.252621  0.079258  0.007314  ...  0.262591  0.208325  0.293593
1.5  0.414556  0.090654 -0.085467  ... -0.092057 -0.005428  0.256943
2.2  0.263545  0.216549  0.023379  ...  0.299306  0.234699  0.442909
2.3 -0.177460  0.127950  0.301078  ...  0.118695  0.012996  0.064717
2.4  0.134365  0.164359  0.113957  ...  0.278173  0.311612  0.158740
4.1  0.023069  0.189260  0.190667  ...  0.152832  0.147325  0.038604
8    0.285511 -0.094444 -0.075884  ...  0.037874  0.271216  0.161214
1.6  0.393903  0.122855  0.025761  ...  0.087541  0.271925  0.463088
1.7  0.226420  0.249154 -0.029013  ...  1.000000  0.377333  0.224805
2.5  0.230202  0.077646  0.036264  ...  0.377333  1.000000  0.339484
2.6  0.548273  0.126047 -0.086475  ...  0.224805  0.339484  1.000000

[19 rows x 19 columns]

In [11]:
data.cov()

3         4         2  ...       1.7       2.5       2.6
3    0.331283  0.065138 -0.105256  ...  0.061644  0.054235  0.603019
4    0.065138  0.662007  0.030752  ...  0.095890  0.025860  0.195974
2   -0.105256  0.030752  0.249091  ... -0.006849  0.007408 -0.082471
1   -0.011462  0.019849  0.079955  ...  0.018265  0.023856  0.145606
1.1  0.026419  0.019569  0.021526  ...  0.015982  0.010111  0.162753
1.2  0.012580  0.079117  0.076461  ...  0.034247  0.024602  0.241124
1.3  0.036483  0.060945  0.086805  ...  0.020548  0.039838  0.223232
1.4  0.058289  0.018172  0.003355  ...  0.002283  0.007595  0.205107
2.1  0.066816  0.029634  0.001677  ...  0.057078  0.039186  0.257804
1.5  0.075063  0.023204 -0.013419  ... -0.013699 -0.000699  0.154459
2.2  0.127202  0.147750  0.009785  ...  0.118721  0.080561  0.709720
2.3 -0.058149  0.059268  0.085547  ...  0.031963  0.003029  0.070404
2.4  0.067095  0.116019  0.049343  ...  0.114155  0.110661  0.263163
4.1  0.010064  0.116718  0.072127  ...  0.054795  0.045709  0.055913
8    0.356025 -0.166480 -0.082052  ...  0.038813  0.240518  0.667412
1.6  0.175007  0.077160  0.009925  ...  0.031963  0.085919  0.683068
1.7  0.061644  0.095890 -0.006849  ...  0.223744  0.073059  0.203196
2.5  0.054235  0.025860  0.007408  ...  0.073059  0.167552  0.265539
2.6  0.603019  0.195974 -0.082471  ...  0.203196  0.265539  3.651477

[19 rows x 19 columns]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X = data.iloc[:, 1:].values
y = data.iloc[:, 0].values

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [15]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [16]:
X_train.shape, y_train.shape

((132, 18), (132,))

In [17]:
X_test.shape, y_test.shape

((15, 18), (15,))

In [18]:
from sklearn.linear_model import LinearRegression

Lr = LinearRegression()

In [19]:
Lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
y_pred = Lr.predict(X_test)

In [21]:
y_pred

array([2.29888888, 2.85781052, 2.40218237, 2.1206925 , 2.52696235,
       2.78810753, 2.05782863, 2.65699403, 2.49502069, 1.79764219,
       2.53865737, 3.06599113, 2.35945263, 2.39614691, 2.56944045])

In [22]:
y_test

array([2, 3, 3, 1, 2, 3, 2, 3, 2, 2, 2, 3, 2, 2, 3])

In [23]:
from sklearn.metrics import r2_score, mean_squared_error

(1-r2_score(y_pred, y_test))*10 # 70

22.122942276761005

In [24]:
mean_squared_error(y_pred, y_test)

0.21456638913108655

# Logistic Regression

In [25]:
data = {
    "col" : [1, 2, 3, 4],
    "col1" : [2, 3, 4 ,5],
    "col2" : [0, 1, 0, 1]
}

In [26]:
data = pd.DataFrame(data=data)

In [27]:
data

col  col1  col2
0    1     2     0
1    2     3     1
2    3     4     0
3    4     5     1

In [28]:
data.shape

(4, 3)

In [29]:
w = np.random.randn(2, 4)

In [30]:
w[0]

array([-0.06169749, -1.0312091 , -0.75206346, -0.05717423])

In [31]:
data['col'] * w[0]

0   -0.061697
1   -2.062418
2   -2.256190
3   -0.228697
Name: col, dtype: float64

In [32]:
y = w[0] * data['col'] + w[1] * data['col1'] + 1

In [33]:
y

0    2.544481
1   -0.046135
2    3.650185
3   -0.583832
dtype: float64

In [34]:
y_pred = 1/(1+np.exp(-y))
y_pred

0    0.927202
1    0.488468
2    0.974672
3    0.358051
dtype: float64

In [35]:
final_y_pred = [1 if final_y >= 0.5 else 0 for final_y in y_pred]

In [36]:
final_y_pred

[1, 0, 1, 0]

In [37]:
data['col2'], final_y_pred, 

(0    0
 1    1
 2    0
 3    1
 Name: col2, dtype: int64, [1, 0, 1, 0])

In [38]:
from sklearn.metrics import accuracy_score

accuracy_score(data["col2"], final_y_pred)

0.0

In [43]:
log_data = pd.read_csv("lymphography.csv", header=None, names=["A", "B", "C", "D", "E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S"])

In [44]:
log_data.head()


A  B  C  D  E  F  G  H  I  J  K  L  M  N  O  P  Q  R  S
0  3  4  2  1  1  1  1  1  2  1  2  2  2  4  8  1  1  2  2
1  2  3  2  1  1  2  2  1  2  1  3  3  2  3  4  2  2  2  2
2  3  3  2  2  2  2  2  2  2  1  4  3  3  4  8  3  2  2  7
3  3  3  1  1  1  1  2  1  2  1  3  3  4  4  4  3  1  2  6
4  2  3  1  1  1  1  1  1  1  1  2  2  4  3  5  1  2  2  1

In [45]:
log_data.isna().sum()

A    0
B    0
C    0
D    0
E    0
F    0
G    0
H    0
I    0
J    0
K    0
L    0
M    0
N    0
O    0
P    0
Q    0
R    0
S    0
dtype: int64

In [46]:
log_data.dtypes

A    int64
B    int64
C    int64
D    int64
E    int64
F    int64
G    int64
H    int64
I    int64
J    int64
K    int64
L    int64
M    int64
N    int64
O    int64
P    int64
Q    int64
R    int64
S    int64
dtype: object

In [47]:
log_data['E'].value_counts()

1    141
2      7
Name: E, dtype: int64

In [48]:
log_data.shape

(148, 19)

In [49]:
from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()

In [50]:
log_data['E'] = lb.fit_transform(log_data['E'])

In [51]:
log_data.describe()

A           B           C  ...           Q           R           S
count  148.000000  148.000000  148.000000  ...  148.000000  148.000000  148.000000
mean     2.452703    2.743243    1.554054  ...    1.662162    1.790541    2.601351
std      0.575396    0.817509    0.498757  ...    0.474579    0.408305    1.905023
min      1.000000    1.000000    1.000000  ...    1.000000    1.000000    1.000000
25%      2.000000    2.000000    1.000000  ...    1.000000    2.000000    1.000000
50%      2.000000    3.000000    2.000000  ...    2.000000    2.000000    2.000000
75%      3.000000    3.000000    2.000000  ...    2.000000    2.000000    3.000000
max      4.000000    4.000000    2.000000  ...    2.000000    2.000000    8.000000

[8 rows x 19 columns]

In [52]:
log_data.corr()

A         B         C  ...         Q         R         S
A  1.000000  0.147550 -0.358447  ...  0.215118  0.232622  0.544329
B  0.147550  1.000000  0.084322  ...  0.230786  0.082347  0.121657
C -0.358447  0.084322  1.000000  ... -0.037284  0.039273 -0.088141
D -0.054812  0.058310  0.414163  ...  0.104504  0.150359  0.199805
E  0.212651  0.109285  0.199896  ...  0.159152  0.114690  0.398857
F  0.046761  0.217326  0.350223  ...  0.171884  0.137024  0.293236
G  0.118952  0.136961  0.338391  ...  0.095376  0.189623  0.234184
H  0.397742  0.084832  0.024882  ...  0.021535  0.072411  0.425165
I  0.255697  0.085327  0.011253  ...  0.254264  0.210115  0.291669
J  0.411953  0.087863 -0.086410  ... -0.089577 -0.006103  0.257242
K  0.258756  0.208602  0.019828  ...  0.302380  0.232245  0.443495
L -0.181180  0.119311  0.295450  ...  0.124406  0.010498  0.066102
M  0.126130  0.150614  0.106347  ...  0.285772  0.306098  0.160417
N  0.033030  0.202660  0.198146  ...  0.135522  0.151461  0.034870
O  0.291371 -0.079649 -0.067398  ...  0.025157  0.273947  0.157477
P  0.377557  0.102592  0.014942  ...  0.102445  0.262919  0.461958
Q  0.215118  0.230786 -0.037284  ...  1.000000  0.369569  0.226241
R  0.232622  0.082347  0.039273  ...  0.369569  1.000000  0.337953
S  0.544329  0.121657 -0.088141  ...  0.226241  0.337953  1.000000

[19 rows x 19 columns]

In [53]:
log_data.cov()

A         B         C  ...         Q         R         S
A  0.331081  0.069406 -0.102868  ...  0.058742  0.054652  0.596663
B  0.069406  0.668321  0.034381  ...  0.089539  0.027487  0.189465
C -0.102868  0.034381  0.248759  ... -0.008825  0.007998 -0.083747
D -0.012043  0.018202  0.078875  ...  0.018937  0.023442  0.145339
E  0.026062  0.019029  0.021236  ...  0.016088  0.009974  0.161840
F  0.011583  0.076485  0.075198  ...  0.035117  0.024085  0.240485
G  0.034335  0.056168  0.084666  ...  0.022706  0.038840  0.223800
H  0.057639  0.017466  0.003126  ...  0.002574  0.007446  0.203990
I  0.067476  0.031991  0.002574  ...  0.055341  0.039345  0.254826
J  0.074324  0.022523 -0.013514  ... -0.013330 -0.000781  0.153659
K  0.124563  0.142673  0.008274  ...  0.120059  0.079334  0.706839
L -0.059248  0.055433  0.083747  ...  0.033554  0.002436  0.071566
M  0.063017  0.106913  0.046056  ...  0.117761  0.108522  0.265352
N  0.014479  0.126218  0.075290  ...  0.048998  0.047113  0.050607
O  0.364038 -0.141386 -0.072991  ...  0.025924  0.242876  0.651407
P  0.168827  0.065177  0.005792  ...  0.037783  0.083425  0.683903
Q  0.058742  0.089539 -0.008825  ...  0.225225  0.071612  0.204541
R  0.054652  0.027487  0.007998  ...  0.071612  0.166713  0.262870
S  0.596663  0.189465 -0.083747  ...  0.204541  0.262870  3.629114

[19 rows x 19 columns]

In [54]:
log_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       148 non-null    int64
 1   B       148 non-null    int64
 2   C       148 non-null    int64
 3   D       148 non-null    int64
 4   E       148 non-null    int64
 5   F       148 non-null    int64
 6   G       148 non-null    int64
 7   H       148 non-null    int64
 8   I       148 non-null    int64
 9   J       148 non-null    int64
 10  K       148 non-null    int64
 11  L       148 non-null    int64
 12  M       148 non-null    int64
 13  N       148 non-null    int64
 14  O       148 non-null    int64
 15  P       148 non-null    int64
 16  Q       148 non-null    int64
 17  R       148 non-null    int64
 18  S       148 non-null    int64
dtypes: int64(19)
memory usage: 22.1 KB


In [55]:
from sklearn.model_selection import train_test_split

In [56]:
[0, 1, 2, 3]
[-4,-3,-2, -1]
#    datasetname.indexlocation[rows, columns].values -- > Pandas or dataframes to the Numpy data numpy or arrays
X = log_data.iloc[:100, :-1].values
y = log_data.iloc[:100, -1].values

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [58]:
from sklearn.preprocessing import MinMaxScaler

mn = MinMaxScaler()

In [59]:
X_train = mn.fit_transform(X_train)
X_test = mn.fit_transform(X_test)

In [60]:
type(X_train)

numpy.ndarray

In [61]:
X_train.shape, y_train.shape

((80, 18), (80,))

In [62]:
from sklearn.linear_model import LogisticRegression

In [64]:
lg = LogisticRegression()

In [65]:
lg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [66]:
y_pred = lg.predict(X_test)

In [67]:
y_pred, y_test

(array([2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 3, 2, 2, 1, 4, 3, 2, 1, 2]),
 array([1, 3, 1, 2, 2, 1, 3, 1, 1, 1, 1, 4, 5, 2, 3, 3, 4, 3, 2, 1]))

In [68]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [69]:
accuracy_score(y_test, y_pred)

0.3

In [70]:
accuracy_score(y_train, lg.predict(X_train))

0.6625

In [72]:
import seaborn as sns

confusion_matrix(y_test, y_pred)

array([[4, 4, 0, 0, 0],
       [2, 2, 0, 0, 0],
       [1, 3, 0, 1, 0],
       [0, 0, 2, 0, 0],
       [0, 1, 0, 0, 0]])

In [73]:
li = [0, 1, 2, 3, 4]

li[:-1]

[0, 1, 2, 3]

In [74]:
li[-1]

4